import type { UiLanguage } from "./translations";
const keys = ["import_preview", "import_review", "import_replace_warning", "import_undone", "export_failed", "save_saving", "save_error", "save_protected", "save_retry", "import_config", "import_exclusions"];
const es = ["Revisar importación", "Combinar agrega el progreso y conserva tu configuración. Reemplazar restaura el progreso y, en los respaldos JSON, la configuración y los temas incluidos. Puedes deshacer la importación.", "Reemplazar quitará el progreso actual que no aparezca en el archivo.", "Importación deshecha", "No se pudo guardar el archivo. Inténtalo de nuevo.", "Guardando…", "No se pudo guardar. Los cambios siguen en esta sesión.", "Los datos locales no se pudieron leer. Se conservarán hasta recuperar un respaldo.", "Reintentar", "Configuración y temas", "Excepciones de progreso"];
const messages: Record<UiLanguage, string[]> = {
  "ES-LA": es, "ES-ES": es,
  ENG: ["Review import", "Merge adds progress and keeps your settings. Replace restores progress and, for JSON backups, the included settings and themes. You can undo the import.", "Replace removes current progress absent from the file.", "Import undone", "Could not save the file. Please try again.", "Saving…", "Saving failed. Changes remain in this session.", "Local data could not be read. It will be preserved until a backup is restored.", "Retry", "Settings and themes", "Progress exceptions"],
  DEU: ["Import prüfen", "Zusammenführen ergänzt Fortschritt. Ersetzen stellt Fortschritt und bei JSON auch enthaltene Einstellungen und Designs wieder her. Der Import ist rückgängig machbar.", "Ersetzen entfernt Fortschritt, der in der Datei fehlt.", "Import rückgängig gemacht", "Datei konnte nicht gespeichert werden.", "Speichern…", "Speichern fehlgeschlagen. Änderungen bleiben in dieser Sitzung.", "Lokale Daten sind nicht lesbar und bleiben bis zur Wiederherstellung erhalten.", "Erneut versuchen", "Einstellungen und Designs", "Fortschrittsausnahmen"],
  FRA: ["Vérifier l’importation", "Fusionner ajoute la progression. Remplacer restaure la progression et, pour JSON, les paramètres et thèmes inclus. L’importation peut être annulée.", "Remplacer retire la progression absente du fichier.", "Importation annulée", "Impossible d’enregistrer le fichier.", "Enregistrement…", "Échec de l’enregistrement. Les changements restent dans cette session.", "Les données locales sont illisibles et seront conservées jusqu’à la restauration.", "Réessayer", "Paramètres et thèmes", "Exceptions de progression"],
  ITA: ["Verifica importazione", "Unisci aggiunge progressi. Sostituisci ripristina i progressi e, per JSON, impostazioni e temi inclusi. Puoi annullare l’importazione.", "Sostituisci rimuove i progressi assenti nel file.", "Importazione annullata", "Impossibile salvare il file.", "Salvataggio…", "Salvataggio non riuscito. Le modifiche restano nella sessione.", "I dati locali non sono leggibili e saranno conservati fino al ripristino.", "Riprova", "Impostazioni e temi", "Eccezioni dei progressi"],
  JPN: ["インポートを確認", "統合は進捗を追加します。置換は進捗とJSON内の設定・テーマを復元します。インポートは取り消せます。", "置換するとファイルにない現在の進捗が削除されます。", "インポートを取り消しました", "ファイルを保存できませんでした。", "保存中…", "保存に失敗しました。変更はこのセッションに残ります。", "ローカルデータを読めません。復元まで元のデータを保持します。", "再試行", "設定とテーマ", "進捗の例外"],
  KOR: ["가져오기 검토", "병합은 진행도를 추가합니다. 교체는 진행도와 JSON에 포함된 설정 및 테마를 복원합니다. 가져오기를 취소할 수 있습니다.", "교체하면 파일에 없는 현재 진행도가 삭제됩니다.", "가져오기 실행 취소됨", "파일을 저장할 수 없습니다.", "저장 중…", "저장 실패. 변경 사항은 현재 세션에 남아 있습니다.", "로컬 데이터를 읽을 수 없습니다. 복원할 때까지 원본을 보존합니다.", "재시도", "설정 및 테마", "진행도 예외"],
  CHS: ["检查导入", "合并会添加进度。替换会恢复进度及JSON中包含的设置和主题。可以撤销导入。", "替换会删除文件中未包含的当前进度。", "已撤销导入", "无法保存文件。", "正在保存…", "保存失败。更改仍保留在本次会话中。", "无法读取本地数据。恢复备份之前将保留原始数据。", "重试", "设置和主题", "进度例外"],
  CHT: ["檢查匯入", "合併會新增進度。取代會還原進度及JSON內的設定與主題。可復原匯入。", "取代會刪除檔案未包含的目前進度。", "已復原匯入", "無法儲存檔案。", "儲存中…", "儲存失敗。變更仍保留於本次工作階段。", "無法讀取本機資料。還原備份前將保留原始資料。", "重試", "設定與主題", "進度例外"],
};
export function reliabilityCopy(language: UiLanguage, key: string) { const index = keys.indexOf(key); return index < 0 ? undefined : messages[language][index]; }
